version: 2.1

orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    executor:
      name: node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test

workflows:
  version: 2
  main:
    jobs:
      - test
