version: 2.1

orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    environment:
      TZ: "Asia/Tokyo"
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn test
            - codecov/upload:
                file: ./coverage/lcov.info
workflows:
  version: 2
  main:
    jobs:
      - test
