version: 2.1

orbs:
  node: circleci/node@3.0.1
  codecov: codecov/codecov@1.1.1

jobs:
  test:
    environment:
      TZ: "Asia/Tokyo"
    executor:
      name: node/default
      tag: "12.18"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test
      - codecov/upload:
          file: ./coverage/lcov.info
  lint:
    executor:
      name: node/default
      tag: "12.18"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint:prettier
      - run: yarn lint:eslint --format junit --output-file ./reports/eslint.xml
      - store_test_results:
          path: ./reports

workflows:
  version: 2
  main:
    jobs:
      - test
      - lint
