version: 2.1

orbs:
  node: circleci/node@3.0.1
  codecov: codecov/codecov@1.1.1
  docker: circleci/docker@1.4.0

jobs:
  test:
    environment:
      TZ: "Asia/Tokyo"
      DB_DATABASE: "test"
      DB_USER: "test"
      DB_PASSWORD: "test"
    docker:
      - image: cimg/node:12.18
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_DATABASE: "test"
          MYSQL_USER: "test"
          MYSQL_PASSWORD: "test"
        command:
          [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
          ]
    steps:
      - checkout
      - docker/install-docker
      - docker/install-dockerize
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test
      - codecov/upload:
          file: ./coverage/lcov.info
  lint:
    executor:
      name: node/default
      tag: "12.18"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint:prettier
      - run: yarn lint:eslint --format junit --output-file ./reports/eslint.xml
      - store_test_results:
          path: ./reports

workflows:
  version: 2
  main:
    jobs:
      - test
      - lint
