version: "3.7"

services:
  cf-postgresql:
    container_name: cf-postgresql-local
  cf-adminer:
    container_name: cf-adminer-local
    image: adminer
    depends_on:
      - cf-postgresql
    ports:
      - 8080:8080
    networks:
      - cf-network
