version: "3.7"

services:
  cf-postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cf-postgresql-data:/var/lib/mysql
    ports:
      - 5432:5432
    networks:
      - cf-network

volumes:
  cf-postgresql-data:

networks:
  cf-network:
    driver: bridge
